Importamos bibliotecas necesarias

In [4]:
import pandas as pd
import numpy as np
import re
import ast

In [5]:
#Cargamos el dataset movies
df_peliculas= pd.read_csv(r'C:\Users\ignac\OneDrive\Escritorio\Proyecto Individual 1\Archivos\movies_dataset.csv', sep=',')

C:\Users\ignac\AppData\Local\Temp\ipykernel_13512\807444321.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_peliculas= pd.read_csv(r'C:\Users\ignac\OneDrive\Escritorio\Proyecto Individual 1\Archivos\movies_dataset.csv', sep=',')

In [6]:
#Hechamos un vistazo al DataFrame 
df_peliculas

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [7]:
df_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

1-Desanidamos columnas del csv Movies:

In [8]:
#Definimos una funcion para extraer los datos de la clave "name" de las columnas que estan anidadas.
def extraer_name(value):
    try:
        pattern = r"'name':\s+'(.*?)'"
        match = re.findall(pattern, value)
        return ', '.join(match)
    except (TypeError, AttributeError):
        return ''

In [9]:
#Extraemos el nombre de las colecciones de la columna 'belongs_to_collection'
df_peliculas['collection'] = df_peliculas['belongs_to_collection'].apply(extraer_name)
df_peliculas['collection'].head(10)

0              Toy Story Collection
1
2         Grumpy Old Men Collection
3
4    Father of the Bride Collection
5
6
7
8
9             James Bond Collection
Name: collection, dtype: object

In [10]:
#Extraemos el nombre de los géneros de la columna 'genres'
df_peliculas['genre'] = df_peliculas['genres'].apply(extraer_name)
df_peliculas['genre'].head(10)

0           Animation, Comedy, Family
1          Adventure, Fantasy, Family
2                     Romance, Comedy
3              Comedy, Drama, Romance
4                              Comedy
5      Action, Crime, Drama, Thriller
6                     Comedy, Romance
7    Action, Adventure, Drama, Family
8         Action, Adventure, Thriller
9         Adventure, Action, Thriller
Name: genre, dtype: object

In [11]:
#Extraemos el nombre de las compañias de la columna 'production_companies'
df_peliculas['production_company'] = df_peliculas['production_companies'].apply(extraer_name) 
df_peliculas['production_company'].head(10)

0                              Pixar Animation Studios
1    TriStar Pictures, Teitler Film, Interscope Com...
2                         Warner Bros., Lancaster Gate
3               Twentieth Century Fox Film Corporation
4           Sandollar Productions, Touchstone Pictures
5      Regency Enterprises, Forward Pass, Warner Bros.
6    Paramount Pictures, Scott Rudin Productions, M...
7                                 Walt Disney Pictures
8    Universal Pictures, Imperial Entertainment, Si...
9                      United Artists, Eon Productions
Name: production_company, dtype: object

In [12]:
#Extraemos el nombre de los países de producción de la columna 'production_countries'
df_peliculas['production_country'] = df_peliculas['production_countries'].apply(extraer_name)
df_peliculas['production_country'].head(10)

0                    United States of America
1                    United States of America
2                    United States of America
3                    United States of America
4                    United States of America
5                    United States of America
6           Germany, United States of America
7                    United States of America
8                    United States of America
9    United Kingdom, United States of America
Name: production_country, dtype: object

In [13]:
#Extraemos el nombre de los lenguajes de la columna 'spoken_languages'
df_peliculas['language'] = df_peliculas['spoken_languages'].apply(extraer_name)
df_peliculas['language'].head(10)

0                      English
1            English, Français
2                      English
3                      English
4                      English
5             English, Español
6            Français, English
7             English, Deutsch
8                      English
9    English, Pусский, Español
Name: language, dtype: object

In [14]:
#Reemplazamos los valores nulos de la columna de 'revenue' con 0
df_peliculas['revenue'] = df_peliculas['revenue'].fillna(0)

In [15]:
#Reemplazamos los valores nulos de la columna 'budget' con 0
df_peliculas['budget'] = df_peliculas['budget'].fillna(0)

In [16]:
#Eliminamos los valores nulos de la columna 'release_date'
df_peliculas['release_date'] = pd.to_datetime(df_peliculas['release_date'], errors='coerce')

df_peliculas.dropna(subset = ['release_date'], inplace=True)

In [17]:
#Aplicamos el formato "AAAA-mm-dd" a la columna de 'release_date'
df_peliculas['release_date'] = pd.to_datetime(df_peliculas['release_date']).dt.strftime('%Y-%m-%d')

In [18]:
#Creamos la columna 'release_year' que contiene el año de estreno de la pelicula, extraido de la anterior columna
df_peliculas['release_year'] = pd.to_datetime(df_peliculas['release_date']).dt.year

In [19]:
#Creamos la columna 'return' que da como resultado el retorno de inversion de cada pelicula, dividiendo las columnas 'revenue'/'budget'.
#Para que no haya errores al dividir las columnas, convertimos los datos de las columnas 'revenue' y 'budget' a formato numerico.
#En caso de que haya datos no disponibles en las columnas, reemplazaremos por 0.
#Para evitar que haya valores infinitos como resultado, tambien reemplazaremos esos infinitos por 0.

df_peliculas['budget'] = pd.to_numeric(df_peliculas['budget'], errors='coerce')
df_peliculas['revenue'] = pd.to_numeric(df_peliculas['revenue'], errors='coerce')

df_peliculas['return'] = df_peliculas['revenue']/df_peliculas['budget']

df_peliculas['return'] = pd.to_numeric(df_peliculas['return'], errors='coerce').fillna(0)

In [20]:
#Eliminamos las columnas 'video', 'imdb_id', 'adult', 'original_title', 'poster_path', y 'homepage'
df_peliculas.drop(columns=['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage',], inplace = True)

In [21]:
#Como ultimo paso extraemos los ID de las columnas anidadas ya que podriamos llegar a necesitarlos a futuro.
#Utilizamos una funcion similar a la que usamos para extraer los datos de la clave 'name', solo que esta funcion busca valores numericos.
def extraer_id(value):
    try:
        pattern = r"'id':\s*(\d+)"
        match = re.findall(pattern, value)
        return ', '.join(match)
    except (TypeError, AttributeError):
        return ''

In [22]:
#Extraemos los ID de las columnas anidadas
df_peliculas['collection_id'] = df_peliculas['belongs_to_collection'].apply(extraer_id)
df_peliculas['genre_id'] = df_peliculas['genres'].apply(extraer_id)
df_peliculas['company_id'] = df_peliculas['production_companies'].apply(extraer_id)

In [23]:
#Eliminamos las columnas anidadas originales del DataFrame ya que extrajimos sus datos utiles.
df_peliculas.drop(columns=['belongs_to_collection', 'genres', 'production_companies', 'production_countries', 'spoken_languages',], inplace = True)

In [65]:
#Eliminamos columnas que son irrelevantes para este proyecto. Ellas son: 'overview', 'status', y 'tagline'.
df_peliculas.drop(columns = ["overview","status","tagline"], axis = 1, inplace = True)

In [68]:
#Recortamos filas del dataset para reducirlo en mb y poder subirlo a GitHub. Y exportamos el csv modificado.
dataset_movies_modificado = df_peliculas.head(20000).to_csv('C:/Users/ignac/OneDrive/Escritorio/Proyecto Individual 1/HenryLabs-PIMLO/dataset_movies_modificado.csv' , index=False, header=True)

ETL de dataset Credits

In [25]:
#Cargamos el dataset credits
df_creditos = pd.read_csv(r'C:\Users\ignac\OneDrive\Escritorio\Proyecto Individual 1\Archivos\credits.csv', sep=',')

In [26]:
#Hechamos un vistazo al DataFrame
df_creditos

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [37]:
#Desanidamos las columnas 'cast'. Como resultado obtuvimos estas nuevas columnas: 'cast_id', 'cast_character', 'cast_credit_id','cast_gender', 'cast_actor_id',
#'cast_name', 'cast_order' y 'cast_profile_path'.

df_creditos["cast_id"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["cast_id"] for i in x] if isinstance(x,list) else [])

In [38]:
df_creditos["cast_character"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["character"] for i in x] if isinstance(x,list) else [])

In [39]:
df_creditos["cast_credit_id"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["credit_id"] for i in x] if isinstance(x,list) else [])

In [40]:
df_creditos["cast_gender"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["gender"] for i in x] if isinstance(x,list) else [])

In [41]:
df_creditos["cast_actor_id"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["id"] for i in x] if isinstance(x,list) else [])

In [42]:
df_creditos["cast_name"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["name"] for i in x] if isinstance(x,list) else [])

In [43]:
df_creditos["cast_order"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["order"] for i in x] if isinstance(x,list) else [])

In [44]:
df_creditos["cast_profile_path"] = df_creditos["cast"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["profile_path"] for i in x] if isinstance(x,list) else [])

In [46]:
#Eliminamos la columna anidada 'cast'
df_creditos.drop(columns = "cast" , axis=1, inplace=True)

In [48]:
#Desanidamos la columna 'crew'.  Como resultado obtuvimos estas nuevas columnas: 'crew_credit_id', 'crew_department', 'crew_gender', 'crew_id', 'crew_job'
# 'crew_name' y 'crew_profile_path'.

df_creditos["crew_credit_id"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["credit_id"] for i in x] if isinstance(x,list) else [])

In [49]:
df_creditos["crew_department"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["department"] for i in x] if isinstance(x,list) else [])

In [50]:
df_creditos["crew_gender"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["gender"] for i in x] if isinstance(x,list) else [])

In [51]:
df_creditos["crew_id"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["id"] for i in x] if isinstance(x,list) else [])

In [52]:
df_creditos["crew_job"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["job"] for i in x] if isinstance(x,list) else [])

In [53]:
df_creditos["crew_name"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["name"] for i in x] if isinstance(x,list) else [])

In [54]:
df_creditos["crew_profile_path"] = df_creditos["crew"].fillna("[]").apply(ast.literal_eval).apply(lambda x: [i["profile_path"] for i in x] if isinstance(x,list) else [])

In [55]:
#Eliminamos la columna anidada 'crew'
df_creditos.drop(columns = "crew" , axis=1, inplace=True)

In [62]:
#Eliminamos columnas que son irrelevantes para este proyecto. Ellas son: 'Unnamed:0', 'cast_id', 'cast_credit_id', 'cast_gender', 'cast_actor_id', 'cast_order',
#  ' cast_profile_path', 'crew_credit_id', 'crew_gender', 'crew_id' y 'crew_profile_path' .

df_creditos.drop(columns = ["cast_credit_id","cast_order","cast_profile_path","crew_credit_id","crew_profile_path","cast_id","cast_gender","cast_actor_id","crew_gender","crew_id"], axis = 1, inplace = True)

In [71]:
df_creditos.head(5)

,id,cast_character,cast_name,crew_department,crew_job,crew_name
0,862,"[Woody (voice), Buzz Lightyear (voice), Mr. Po...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...","[Directing, Writing, Writing, Writing, Writing...","[Director, Screenplay, Screenplay, Screenplay,...","[John Lasseter, Joss Whedon, Andrew Stanton, J..."
1,8844,"[Alan Parrish, Samuel Alan Parrish / Van Pelt,...","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...","[Production, Writing, Sound, Directing, Editin...","[Executive Producer, Screenplay, Original Musi...","[Larry J. Franco, Jonathan Hensleigh, James Ho..."
2,15602,"[Max Goldman, John Gustafson, Ariel Gustafson,...","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...","[Directing, Writing, Writing, Crew]","[Director, Characters, Writer, Sound Recordist]","[Howard Deutch, Mark Steven Johnson, Mark Stev..."
3,31357,"[Savannah 'Vannah' Jackson, Bernadine 'Bernie'...","[Whitney Houston, Angela Bassett, Loretta Devi...","[Directing, Writing, Production, Production, P...","[Director, Screenplay, Producer, Producer, Pro...","[Forest Whitaker, Ronald Bass, Ronald Bass, Ez..."
4,11862,"[George Banks, Nina Banks, Franck Eggelhoffer,...","[Steve Martin, Diane Keaton, Martin Short, Kim...","[Sound, Camera, Writing, Production, Writing, ...","[Original Music Composer, Director of Photogra...","[Alan Silvestri, Elliot Davis, Nancy Meyers, N..."

In [70]:
#Recortamos filas del dataset para reducirlo en mb y poder subirlo a GitHub. Y exportamos el csv modificado.
dataset_credits_modificado = df_creditos.head(20000).to_csv('C:/Users/ignac/OneDrive/Escritorio/Proyecto Individual 1/HenryLabs-PIMLO/dataset_credits_modificado.csv' , index=False, header=True)